name: Check & deploy to DockerHub

on:
  push:
    branches:
      - 'master'

jobs:
  perform-check:
    uses: ./.github/workflows/test_lint.yml
  docker:
    runs-on: ubuntu-latest
    environment: DockerHub
    needs:
      - perform-check
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: edgeneko/neko-image-gallery:latest
